<?php
/**
 * Created by PhpStorm.
 * User: lxh
 * Date: 2021-10-19
 * Time: 20:48
 */

namespace App\HttpController;


use EasySwoole\Http\AbstractInterface\Controller;

class BaseController extends Controller
{
    protected function onRequest(string $action): ?bool
    {

        return parent::onRequest($action); // TODO: Change the autogenerated stub
    }


}